### ISSUE TITLE
Property Name Wrong

### ISSUE THREAD

**Issue by dvpalex** [marcoatribeiro/FluentEmail.MailerSend#2]
FluentEmail.MailerSend/Models/Variable.cs

 The property Substituitions is wrong, correct name is Substitutions.

The Mailerserver return : {\"message\":\"The variables.0.substitutions field is required when variables.0.email is present.\",\"errors\":{\"variables.0.substitutions\":[\"The variables.0.substitutions field is required when variables.0.email is present.\"]}}", because name is wrote

**Comment by marcoatribeiro** [comment]
Thanks! Typo fixed.
